apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: subratasikdar2021/3-tier-devsecops-backend:latest
          ports:
            - containerPort: 8080
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
    - name: http-5000
      port: 5000
      targetPort: 5000
  selector:
    app: backend
