sonar.projectKey=3-Tier-DevSecOps-Mega-Project
sonar.projectName=3-Tier-DevSecOps-Mega-Project
sonar.token=sqa_02689b94e54684bc461662bc44ce51107e614bff
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**
